<?php

/**
 * BaseRessourceFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_ressource
 * @property integer $id_file
 * @property Ressource $Ressource
 * @property File $File
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getIdRessource()  Returns the current record's "id_ressource" value
 * @method integer       getIdFile()       Returns the current record's "id_file" value
 * @method Ressource     getRessource()    Returns the current record's "Ressource" value
 * @method File          getFile()         Returns the current record's "File" value
 * @method RessourceFile setId()           Sets the current record's "id" value
 * @method RessourceFile setIdRessource()  Sets the current record's "id_ressource" value
 * @method RessourceFile setIdFile()       Sets the current record's "id_file" value
 * @method RessourceFile setRessource()    Sets the current record's "Ressource" value
 * @method RessourceFile setFile()         Sets the current record's "File" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessourceFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource_file');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_ressource', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_file', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ressource', array(
             'local' => 'id_ressource',
             'foreign' => 'id'));

        $this->hasOne('File', array(
             'local' => 'id_file',
             'foreign' => 'id'));
    }
}