<?php

/**
 * BaseRessourceCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_ressource
 * @property integer $id_category
 * @property Ressource $Ressource
 * @property Category $Category
 * 
 * @method integer           getId()           Returns the current record's "id" value
 * @method integer           getIdRessource()  Returns the current record's "id_ressource" value
 * @method integer           getIdCategory()   Returns the current record's "id_category" value
 * @method Ressource         getRessource()    Returns the current record's "Ressource" value
 * @method Category          getCategory()     Returns the current record's "Category" value
 * @method RessourceCategory setId()           Sets the current record's "id" value
 * @method RessourceCategory setIdRessource()  Sets the current record's "id_ressource" value
 * @method RessourceCategory setIdCategory()   Sets the current record's "id_category" value
 * @method RessourceCategory setRessource()    Sets the current record's "Ressource" value
 * @method RessourceCategory setCategory()     Sets the current record's "Category" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessourceCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_ressource', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_category', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ressource', array(
             'local' => 'id_ressource',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'id_category',
             'foreign' => 'id'));
    }
}