<?php

/**
 * BaseRessource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $description
 * @property integer $state
 * @property Doctrine_Collection $ressource_categories
 * @property Doctrine_Collection $ressource_files
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getTitle()                Returns the current record's "title" value
 * @method clob                getDescription()          Returns the current record's "description" value
 * @method integer             getState()                Returns the current record's "state" value
 * @method Doctrine_Collection getRessourceCategories()  Returns the current record's "ressource_categories" collection
 * @method Doctrine_Collection getRessourceFiles()       Returns the current record's "ressource_files" collection
 * @method Ressource           setId()                   Sets the current record's "id" value
 * @method Ressource           setTitle()                Sets the current record's "title" value
 * @method Ressource           setDescription()          Sets the current record's "description" value
 * @method Ressource           setState()                Sets the current record's "state" value
 * @method Ressource           setRessourceCategories()  Sets the current record's "ressource_categories" collection
 * @method Ressource           setRessourceFiles()       Sets the current record's "ressource_files" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('state', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RessourceCategory as ressource_categories', array(
             'local' => 'id',
             'foreign' => 'id_ressource'));

        $this->hasMany('RessourceFile as ressource_files', array(
             'local' => 'id',
             'foreign' => 'id_ressource'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
    }
}