<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory {

    public function ReadyToChoice() {
        return sprintf('%s', $this->getIndentedName());
    }

    public function getParentId() {
        if (!$this->getNode()->isValidNode() || $this->getNode()->isRoot()) {
            return null;
        }

        $parent = $this->getNode()->getParent();

        return $parent['id'];
    }

    public function getIndentedName() {
        return str_repeat('- ', $this['level']) . $this['name'];
    }

}