generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, name]
        title:   Gestion des categorys
        max_per_page: 999999
        batch_actions:
          order:
            label: Mettre à jour
          _delete: ~
        object_actions:
          new:
            label: Ajouter fils
          _edit:    ~
          _delete:  ~
        actions:
          _new:
            label: Ajouter racine
      filter: ~
      form: ~
      edit:
        title: Editer category "%%name%%"
      new:     ~
