---
detect_relations: true
options:
  collate: latin1_swedish_ci
  charset: latin1
  type: InnoDB

Ressource: 
  actAs:
    Timestampable: ~
    SoftDelete: ~
    Sluggable: 
      fields: [title]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(255)
    description:
      type: clob(65535)
    state:
      type: integer(4)
  options:
    charset: utf8
    collate: utf8_general_ci

RessourceCategory:
  tableName: ressource_category
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    id_ressource:
      type: integer(4)
    id_category:
      type: integer(4)
  relations:
    Ressource:
      class: Ressource
      local: id_ressource
      foreign: id
      foreignAlias: ressource_categories
    Category:
      class: Category
      local: id_category
      foreign: id
      foreignAlias: ressource_categories
  options:
    charset: utf8
    collate: utf8_general_ci

Category: 
  actAs:
    Timestampable: ~
    SoftDelete: ~
    Sluggable: 
      fields: [name]
    NestedSet:      
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
  options:
    charset: utf8
    collate: utf8_general_ci

RessourceFile:
  tableName: ressource_file
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    id_ressource:
      type: integer(4)
    id_file:
      type: integer(4)
  relations:
    Ressource:
      class: Ressource
      local: id_ressource
      foreign: id
      foreignAlias: ressource_files
    File:
      class: File
      local: id_file
      foreign: id
      foreignAlias: ressource_files
  options:
    charset: utf8
    collate: utf8_general_ci

File:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
    size:
      type: string(255)
    path:
      type: string(45)
  options:
    charset: utf8
    collate: utf8_general_ci

